# Generated by Django 5.2.7 on 2025-10-16 11:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Напишите название книги')),
                ('description', models.TextField(verbose_name='Напишите описание книги')),
                ('image', models.ImageField(upload_to='books/', verbose_name='Выберите изображение книги')),
                ('quantity_page', models.PositiveIntegerField(verbose_name='Количество страниц')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Автор книги')),
                ('book_audio', models.URLField(blank=True, null=True, verbose_name='Ссылка на аудиокнигу')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'книга',
                'verbose_name_plural': 'книги',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'человек',
                'verbose_name_plural': 'люди',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'тур',
                'verbose_name_plural': 'туры',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Оцените книгу от 1 до 5')),
                ('review_text', models.TextField(verbose_name='Ваше мнение о книге')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.books')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.person')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.tour')),
            ],
            options={
                'verbose_name': 'регистрация',
                'verbose_name_plural': 'регистрации',
            },
        ),
    ]
