# Generated by Django 5.2.7 on 2025-10-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_audio',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на аудиокнигу'),
        ),
    ]
