# Generated by Django 5.2.7 on 2025-10-20 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
        ('books', '0002_alter_books_book_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название корзины')),
                ('email', models.EmailField(max_length=254, verbose_name='Email пользователя')),
                ('address', models.TextField(blank=True, verbose_name='Адрес доставки')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='book',
        ),
        migrations.CreateModel(
            name='BuyedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=100, null=True, verbose_name='Имя покупателя')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('buying_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='В обработке', verbose_name='Статус заказа')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books')),
            ],
            options={
                'verbose_name': 'купленная книга',
                'verbose_name_plural': 'купленные книги',
            },
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
